version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: pinterest-backend:latest
    container_name: pinterest-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/downloads:/app/downloads
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: pinterest-frontend:latest
    container_name: pinterest-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    depends_on:

      - backend      - ./backend/downloads:/app/downloads

    ports:

      - "8080:80"    expose:    container_name: pinterest-backend    restart: unless-stopped

    networks:

      - app-network      - "5000"



networks:    networks:    restart: unless-stopped    environment:

  app-network:

    driver: bridge      - app-network



volumes:    environment:      FLASK_ENV: production

  downloads:
  web:

    build:      FLASK_ENV: production    expose:

      context: ./frontend

      args:      PYTHONUNBUFFERED: 1      - "5000"

        VITE_API_URL: /

    image: yttmp3-frontend:latest    volumes:

    container_name: pinterest-frontend

    restart: unless-stopped      - ./backend/downloads:/app/downloads  web:

    depends_on:

      - backend    expose:    build:

    ports:

      - "8080:80"      - "5000"      context: ./frontend

    networks:

      - app-network    networks:      args:



networks:      - app-network        VITE_API_URL: /

  app-network:

    driver: bridge    image: yttmp3-frontend:latest


  web:    restart: unless-stopped

    build:    depends_on:

      context: ./frontend      - backend

      args:    ports:

        VITE_API_URL: /      - "8080:80"

    image: yttmp3-frontend:latest

    container_name: pinterest-frontendnetworks:

    restart: unless-stopped  default:

    depends_on:    name: yttmp3-network

      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
