version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: yttmp3-backend:latest
    restart: unless-stopped
    environment:
      FLASK_ENV: production
    expose:
      - "5000"

  web:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /
    image: yttmp3-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

networks:
  default:
    name: yttmp3-network
