services:
  backend:
    build:
      context: ./backend
    image: pinterest-backend:latest
    container_name: pinterest-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/downloads:/app/downloads
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-nextjs
      args:
        BACKEND_URL: http://backend:5000
    image: pinterest-frontend-nextjs:latest
    container_name: pinterest-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "8080:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
